title: 98548J Notebook
description: This webpage contains the engineering notebook for the VRC team 98548J.
theme: just-the-docs

color_scheme: modifications
search_enabled: true
favicon_ico: "/assets/Fedora.ico"

defaults:

  - scope:
      path: "docs"
    values:
      layout: "doc"


url: https://98548J.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
